from PyQt5 import QtCore, QtGui, QtWidgets


class UiMainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(465, 550)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setGeometry(QtCore.QRect(10, 90, 451, 71))
        self.widget_2.setObjectName("widget_2")
        self.widget_4 = QtWidgets.QWidget(self.widget_2)
        self.widget_4.setGeometry(QtCore.QRect(90, 0, 91, 71))
        self.widget_4.setObjectName("widget_4")
        self.label_3 = QtWidgets.QLabel(self.widget_4)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 58, 16))
        self.label_3.setObjectName("label_3")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.widget_4)
        self.lineEdit_3.setGeometry(QtCore.QRect(10, 30, 71, 28))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.widget = QtWidgets.QWidget(self.widget_2)
        self.widget.setGeometry(QtCore.QRect(0, 0, 91, 71))
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(10, 10, 58, 16))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setGeometry(QtCore.QRect(10, 30, 61, 28))
        self.lineEdit.setObjectName("lineEdit")
        self.widget_3 = QtWidgets.QWidget(self.widget)
        self.widget_3.setGeometry(QtCore.QRect(0, 0, 91, 71))
        self.widget_3.setObjectName("widget_3")
        self.label_2 = QtWidgets.QLabel(self.widget_3)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 58, 16))
        self.label_2.setObjectName("label_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget_3)
        self.lineEdit_2.setGeometry(QtCore.QRect(10, 30, 61, 28))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.widget_5 = QtWidgets.QWidget(self.widget_2)
        self.widget_5.setGeometry(QtCore.QRect(180, 0, 91, 71))
        self.widget_5.setObjectName("widget_5")
        self.label_4 = QtWidgets.QLabel(self.widget_5)
        self.label_4.setGeometry(QtCore.QRect(20, 30, 58, 16))
        self.label_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_4.setStyleSheet("")
        self.label_4.setObjectName("label_4")
        self.widget_6 = QtWidgets.QWidget(self.widget_2)
        self.widget_6.setGeometry(QtCore.QRect(270, 0, 91, 71))
        self.widget_6.setObjectName("widget_6")
        self.label_5 = QtWidgets.QLabel(self.widget_6)
        self.label_5.setGeometry(QtCore.QRect(20, 30, 58, 16))
        self.label_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_5.setStyleSheet("")
        self.label_5.setObjectName("label_5")
        self.widget_7 = QtWidgets.QWidget(self.widget_2)
        self.widget_7.setGeometry(QtCore.QRect(360, 0, 91, 71))
        self.widget_7.setObjectName("widget_7")
        self.label_6 = QtWidgets.QLabel(self.widget_7)
        self.label_6.setGeometry(QtCore.QRect(20, 30, 58, 16))
        self.label_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_6.setStyleSheet("")
        self.label_6.setObjectName("label_6")
        self.widget_8 = QtWidgets.QWidget(self.centralwidget)
        self.widget_8.setGeometry(QtCore.QRect(10, 10, 451, 80))
        self.widget_8.setObjectName("widget_8")
        self.label_7 = QtWidgets.QLabel(self.widget_8)
        self.label_7.setGeometry(QtCore.QRect(150, 10, 141, 61))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.widget_9 = QtWidgets.QWidget(self.centralwidget)
        self.widget_9.setGeometry(QtCore.QRect(9, 159, 451, 361))
        self.widget_9.setObjectName("widget_9")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 465, 22))
        self.menubar.setObjectName("menubar")
        self.menuContador_de_C_digos = QtWidgets.QMenu(self.menubar)
        self.menuContador_de_C_digos.setObjectName("menuContador_de_C_digos")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuContador_de_C_digos.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "Código"))
        self.label.setText(_translate("MainWindow", "Tamaño"))
        self.label_2.setText(_translate("MainWindow", "Tamaño"))
        self.label_4.setText(_translate("MainWindow", "Cliente"))
        self.label_5.setText(_translate("MainWindow", "Pieza"))
        self.label_6.setText(_translate("MainWindow", "Cantidad"))
        self.label_7.setText(_translate("MainWindow", "Contador"))
        self.menuContador_de_C_digos.setTitle(
            _translate("MainWindow", "Contador de Códigos")
        )
