from PyQt5 import QtCore, QtGui, QtWidgets


class UiMainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(465, 550)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.counter_container = QtWidgets.QWidget(self.centralwidget)
        self.counter_container.setGeometry(QtCore.QRect(10, 90, 451, 101))
        self.counter_container.setObjectName("counter_container")
        self.code_container = QtWidgets.QWidget(self.counter_container)
        self.code_container.setGeometry(QtCore.QRect(90, 0, 91, 71))
        self.code_container.setObjectName("code_container")
        self.code_label = QtWidgets.QLabel(self.code_container)
        self.code_label.setGeometry(QtCore.QRect(10, 10, 58, 16))
        self.code_label.setObjectName("code_label")
        self.code = QtWidgets.QLineEdit(self.code_container)
        self.code.setGeometry(QtCore.QRect(10, 30, 71, 28))
        self.code.setObjectName("code")
        self.size_container = QtWidgets.QWidget(self.counter_container)
        self.size_container.setGeometry(QtCore.QRect(0, 0, 91, 71))
        self.size_container.setObjectName("size_container")
        self.size_label = QtWidgets.QLabel(self.size_container)
        self.size_label.setGeometry(QtCore.QRect(10, 10, 58, 16))
        self.size_label.setObjectName("size_label")
        self.size = QtWidgets.QLineEdit(self.size_container)
        self.size.setGeometry(QtCore.QRect(10, 30, 61, 28))
        self.size.setObjectName("size")
        self.client_container = QtWidgets.QWidget(self.counter_container)
        self.client_container.setGeometry(QtCore.QRect(180, 0, 91, 71))
        self.client_container.setObjectName("client_container")
        self.client_label = QtWidgets.QLabel(self.client_container)
        self.client_label.setGeometry(QtCore.QRect(10, 10, 58, 16))
        self.client_label.setObjectName("client_label")
        self.client = QtWidgets.QLineEdit(self.client_container)
        self.client.setGeometry(QtCore.QRect(10, 30, 71, 28))
        self.client.setReadOnly(True)
        self.client.setObjectName("client")
        self.piece_container = QtWidgets.QWidget(self.counter_container)
        self.piece_container.setGeometry(QtCore.QRect(270, 0, 91, 71))
        self.piece_container.setObjectName("piece_container")
        self.piece_label = QtWidgets.QLabel(self.piece_container)
        self.piece_label.setGeometry(QtCore.QRect(10, 10, 58, 16))
        self.piece_label.setObjectName("piece_label")
        self.piece = QtWidgets.QLineEdit(self.piece_container)
        self.piece.setGeometry(QtCore.QRect(10, 30, 71, 28))
        self.piece.setReadOnly(True)
        self.piece.setObjectName("piece")
        self.count_container = QtWidgets.QWidget(self.counter_container)
        self.count_container.setGeometry(QtCore.QRect(360, 0, 91, 71))
        self.count_container.setObjectName("count_container")
        self.count_label = QtWidgets.QLabel(self.count_container)
        self.count_label.setGeometry(QtCore.QRect(10, 10, 58, 16))
        self.count_label.setObjectName("count_label")
        self.count = QtWidgets.QLineEdit(self.count_container)
        self.count.setGeometry(QtCore.QRect(10, 30, 71, 28))
        self.count.setReadOnly(True)
        self.count.setObjectName("count")
        self.end_count = QtWidgets.QPushButton(self.counter_container)
        self.end_count.setGeometry(QtCore.QRect(0, 70, 121, 31))
        self.end_count.setStyleSheet("")
        self.end_count.setDefault(False)
        self.end_count.setFlat(False)
        self.end_count.setObjectName("end_count")
        self.title_container = QtWidgets.QWidget(self.centralwidget)
        self.title_container.setGeometry(QtCore.QRect(10, 10, 451, 80))
        self.title_container.setObjectName("title_container")
        self.title = QtWidgets.QLabel(self.title_container)
        self.title.setGeometry(QtCore.QRect(140, 10, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.title.setFont(font)
        self.title.setObjectName("title")
        self.list_container = QtWidgets.QWidget(self.centralwidget)
        self.list_container.setGeometry(QtCore.QRect(10, 250, 451, 271))
        self.list_container.setObjectName("list_container")
        self.list = QtWidgets.QListWidget(self.list_container)
        self.list.setGeometry(QtCore.QRect(0, 0, 451, 361))
        self.list.setStyleSheet("")
        self.list.setObjectName("list")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Contador de Códigos"))
        self.code_label.setText(_translate("MainWindow", "Código"))
        self.size_label.setText(_translate("MainWindow", "Tamaño"))
        self.client_label.setText(_translate("MainWindow", "Cliente"))
        self.piece_label.setText(_translate("MainWindow", "Pieza"))
        self.count_label.setText(_translate("MainWindow", "Cantidad"))
        self.end_count.setText(_translate("MainWindow", "Finalizar Conteo"))
        self.title.setText(_translate("MainWindow", "Contador"))
